sudo: false

language: node_js
node_js:
  - "11"

cache:
  directories:
    - node_modules
    - node_cache
    - $HOME/.npm

before_install:
  - npm i -g

script:
  - npm run build

notifications:
  email: false
